Repository wbhoomika/16April23-MLSA-OS-Talk, pull requests merged in 2023-04, with the labels that each got.

#1 Testing PR
  README.md
Labels: good first issue

#2 Test branch ss
  EvenOdd.cpp
  power.cpp
Labels: good first issue

#3 Fix `isEven` function
  EvenOdd.cpp
Labels: enhancement, good first issue

#4 function-sum
  functionSum.cpp
  functionSum.exe
Labels: good first issue

#7 created pattern.cpp
  pattern.cpp
Labels: good first issue

#8 Adding sort_array.cpp
  sort_array.cpp
Labels: good first issue

#9 Basic `Clean up`, `formatted` with `prettier` and `Update`
  .vscode/c_cpp_properties.json
  EvenOdd.cpp
  README.md
  functionSum.cpp
  functionSum.exe
  pattern.cpp
  power.cpp
  sort_array.cpp
Labels: documentation, enhancement

#10 Add files via upload
  multiply.exe
Labels: good first issue
